config/routes.rb
Cookbook::Application.routes.draw do
  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  match "signup" => 'authors#new', :as => "signup"
  match "login" => 'sessions#new', :as => "login"
  match "logout" => 'sessions#destroy', :as => "logout"

  resources :sessions, :except => [:edit, :update, :index]

  resources :steps
  resources :recipes
  resources :comments
  resources :ingredients

  root :to => 'recipes#index'

end

app/models/comments.rb
class Comments < ActiveRecord::Base
  attr_accessible :content, :title
end

app/models/ingredients.rb
class Ingredients < ActiveRecord::Base
  attr_accessible :content, :title
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  attr_accessible :content, :title
end

app/models/step.rb
class Step < ActiveRecord::Base
  attr_accessible :content, :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :require_authentication
  before_filter :setup_twilio_client

  def current_user
      if session[:user_id]
        @current_user = User.find(session[:user_id])
      end
    end
    helper_method :current_user
  end

  def require_authentication
    if current_user.nil?
      redirect_to root_path :alert => "Dawg, you need to be logged in!"
  	end

end

  def setup_twilio_client
    if @twilio_client.nil?
		@twilio_client = Twilio::REST::Client.new(
		account_sid = 'ACc470d2edc2cb48e85ed9dea68270db7b'
		auth_token = '{{ 8054f891d8bcba28e205774970d6066f }}')
	end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.all
  end

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.create(params[:comment])
  end

  def edit
    @comment = Comment.new(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])

    if @comment.update_attributes(params[:comment])
      redirect_to "/recipes/index"
    else
      render :edit
      # In Sinatra, it would be `erb :edit`.
    end
  end

  def destroy
    @comment = Comment.find(params[:id])

    @comment.destroy

    redirect_to "/comment/index"
  end

  def show
    @comment = Comment.find(params[:id])
  end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
    @ingredients = Ingredient.all
  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.create(params[:ingredient])
  end

  def edit
    @ingredient = Ingredient.new(params[:id])
  end

  def update
    @ingredient = Ingredient.find(params[:id])

    if @ingredient.update_attributes(params[:ingredient])
      redirect_to "/recipes/index"
    else
      render :edit
      # In Sinatra, it would be `erb :edit`.
    end
  end

  def destroy
    @ingredient = Ingredient.find(params[:id])

    @ingredient.destroy

    redirect_to "/ingredients/index"
  end

  def show
    @ingredient = Ingredient.find(params[:id]) 
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.create(params[:recipe])
  end

  def edit
    @recipe = Recipe.new(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])

    if @recipe.update_attributes(params[:recipe])
      redirect_to "/recipes/index"
    else
      render :edit
      # In Sinatra, it would be `erb :edit`.
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])

    @recipe.destroy

    redirect_to "/recipes/index"
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :require_authentication

  def new
  end

  def create
  	user = User.find_by_email(params[:email])

  if user && user.authentication(params[:password])
  	session[:user_id] = user.user_id
  	redirect_to root_path, :notice => "Congrats! You logged in dawg."
  else
  	flash.now[:alet] = "Dawg, you email or password ain't corrent. You sure you got that right?"
  	render :new
  end
end


def destroy
  	session[:user_id] = nil
  	redirect_to root_path, :notice => "Aight then, you just logged out"
 end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  # GET /steps
  # GET /steps.json
  def index
    @steps = Step.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @steps }
    end
  end

  # GET /steps/1
  # GET /steps/1.json
  def show
    @step = Step.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @step }
    end
  end

  # GET /steps/new
  # GET /steps/new.json
  def new
    @step = Step.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @step }
    end
  end

  # GET /steps/1/edit
  def edit
    @step = Step.find(params[:id])
  end

  # POST /steps
  # POST /steps.json
  def create
    @step = Step.new(params[:step])

    respond_to do |format|
      if @step.save
        format.html { redirect_to @step, notice: 'Step was successfully created.' }
        format.json { render json: @step, status: :created, location: @step }
      else
        format.html { render action: "new" }
        format.json { render json: @step.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /steps/1
  # PUT /steps/1.json
  def update
    @step = Step.find(params[:id])

    respond_to do |format|
      if @step.update_attributes(params[:step])
        format.html { redirect_to @step, notice: 'Step was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @step.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /steps/1
  # DELETE /steps/1.json
  def destroy
    @step = Step.find(params[:id])
    @step.destroy

    respond_to do |format|
      format.html { redirect_to steps_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

<%= form_for @comment, :url => {:action => "update"} do |f| %>
  <label>Title</label>
  <%= f.text_field :title %><br>

  <label>Content</label>
  <%= f.text_area :content %><br>

  <%= f.submit %>
<% end %>

app/views/comments/index.html.erb
<h1>Comments</h1>
<p>Find me in app/views/comments/index.html.erb</p>

<% @comments.each do |comment| %>
  <p>
    <%= link_to(comment.title, "/recipe/#{comment.id}") %> -
    <%= link_to("Edit", "/comments/edit/#{comment.id}") %> -
    <%= link_to("Delete", "/recipes/destroy/#{recipe.id}", :method => :delete) %>
  </p>
<% end %>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

<%= form_for @comment, :url => {:action => "create"} do |f| %>  <!--#''-->
  <label>Title</label>
  <%= f.text_field :title %><br>

  <label>Content</label>
  <%= f.text_area :content %><br>

  <%= f.submit %>
<% end %>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/recipes/show.html.erb</p>

<%= @comment.title %>

<p><%= @comment.content %></p>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/ingredients/create.html.erb
<h1>Ingredients#create</h1>
<p>Find me in app/views/incredients/create.html.erb</p>

app/views/ingredients/destroy.html.erb
<h1>Ingredients#destroy</h1>
<p>Find me in app/views/ingredients/destroy.html.erb</p>

app/views/ingredients/edit.html.erb
<h1>Ingredients#edit</h1>
<p>Find me in app/views/ingredients/edit.html.erb</p>

<%= form_for @ingredient, :url => {:action => "update"} do |f| %>
  <label>Title</label>
  <%= f.text_field :title %><br>

  <label>Content</label>
  <%= f.text_area :content %><br>

  <%= f.submit %>
<% end %>

app/views/ingredients/index.html.erb
<h1>Ingredients</h1>
<p>Find me in app/views/ingredients/index.html.erb</p>

<% @ingredients.each do |ingredient| %>
  <p>
    <%= link_to(ingredient.title, "/ingredient/#{ingredient.id}") %> -
    <%= link_to("Edit", "/ingredients/edit/#{ingredient.id}") %> -
    <%= link_to("Delete", "/ingredients/destroy/#{ingredient.id}", :method => :delete) %>
  </p>
<% end %>

app/views/ingredients/new.html.erb
<h1>Ingredients#new</h1>
<p>Find me in app/views/ingredients/new.html.erb</p>

<%= form_for @ingredient, :url => {:action => "create"} do |f| %>  <!--#''-->
  <label>Title</label>
  <%= f.text_field :title %><br>

  <label>Content</label>
  <%= f.text_area :content %><br>

  <%= f.submit %>
<% end %>

app/views/ingredients/show.html.erb
<h1>Ingredients#show</h1>
<p>Find me in app/views/ingredients/show.html.erb</p>

<%= @ingredient.title %>

<p><%= @ingredient.content %></p>

app/views/ingredients/update.html.erb
<h1>Ingredients#update</h1>
<p>Find me in app/views/ingredients/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cookbook</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/recipes/destroy.html.erb
<h1>Recipes#destroy</h1>
<p>Find me in app/views/recipes/destroy.html.erb</p>

app/views/recipes/edit.html.erb
<h1>Recipes#edit</h1>
<p>Find me in app/views/recipes/edit.html.erb</p>

<%= form_for @recipe, :url => {:action => "update"} do |f| %>
  <label>Title</label>
  <%= f.text_field :title %><br>

  <label>Content</label>
  <%= f.text_area :content %><br>

  <%= f.submit %>
<% end %>

app/views/recipes/index.html.erb
<h1>Recipes</h1>
<p>Find me in app/views/recipes/index.html.erb</p>

<% @recipes.each do |recipe| %>
  <p>
    <%= link_to(recipe.title, "/recipe/#{recipe.id}") %> -
    <%= link_to("Edit", "/recipes/edit/#{recipe.id}") %> -
    <%= link_to("Delete", "/recipes/destroy/#{recipe.id}", :method => :delete) %>
  </p>
<% end %>

app/views/recipes/new.html.erb
<h1>Recipes#new</h1>
<p>Find me in app/views/recipes/new.html.erb</p>

<%= form_for @recipe, :url => {:action => "create"} do |f| %>  <!--#''-->
  <label>Title</label>
  <%= f.text_field :title %><br>

  <label>Content</label>
  <%= f.text_area :content %><br>

  <%= f.submit %>
<% end %>

app/views/recipes/show.html.erb
<h1>Recipes#show</h1>
<p>Find me in app/views/recipes/show.html.erb</p>

<%= @recipe.title %>

<p><%= @recipe.content %></p>

app/views/recipes/update.html.erb
<h1>Recipes#update</h1>
<p>Find me in app/views/recipes/update.html.erb</p>

app/views/steps/_form.html.erb
<%= form_for(@step) do |f| %>
  <% if @step.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@step.errors.count, "error") %> prohibited this step from being saved:</h2>

      <ul>
      <% @step.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/steps/edit.html.erb
<h1>Editing step</h1>

<%= render 'form' %>

<%= link_to 'Show', @step %> |
<%= link_to 'Back', steps_path %>

app/views/steps/index.html.erb
<h1>Listing steps</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @steps.each do |step| %>
  <tr>
    <td><%= step.title %></td>
    <td><%= step.content %></td>
    <td><%= link_to 'Show', step %></td>
    <td><%= link_to 'Edit', edit_step_path(step) %></td>
    <td><%= link_to 'Destroy', step, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Step', new_step_path %>

app/views/steps/new.html.erb
<h1>New step</h1>

<%= render 'form' %>

<%= link_to 'Back', steps_path %>

app/views/steps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @step.title %>
</p>

<p>
  <b>Content:</b>
  <%= @step.content %>
</p>


<%= link_to 'Edit', edit_step_path(@step) %> |
<%= link_to 'Back', steps_path %>